import os
import subprocess
import img2pdf
from pypdf import PdfWriter, PdfReader
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as ReportLabImage
from reportlab.lib.units import inch

def generate_summary_pdf(data, output_path):
    """
    Generates a PDF summary matching the specific table layout.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()

    # 1. Header (Logo)
    logo_path = os.path.abspath("static/images/logo.jpg")
    if os.path.exists(logo_path):
        # Match create_overlay dimensions for consistency
        # Width 1.5 inch, Height 0.8 inch
        im = ReportLabImage(logo_path, width=1.5*inch, height=0.8*inch, kind='proportional')
        im.hAlign = 'LEFT'
        story.append(im)
    else:
        # Fallback if logo missing
        header_style = ParagraphStyle(
            'Header',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2563eb'),
            alignment=0, # Left
            spaceAfter=20
        )
        story.append(Paragraph("Triumph Consultants", header_style))
    
    story.append(Spacer(1, 20))

    # Title: PROFILE SUMMARY
    title_style = ParagraphStyle(
        'ProfileSummary',
        parent=styles['Heading2'],
        fontSize=14,
        alignment=1, # Center
        spaceAfter=10,
        fontName='Helvetica-Bold',
        textColor=colors.black
    )
    story.append(Paragraph("PROFILE SUMMARY", title_style))
    story.append(Spacer(1, 10))

    # 2. Data Table
    # Columns: S.No, Field Name, Details
    table_data = [
        ["S.No", "Field", "Details"] # Header Row
    ]

    # Field Mapping (Order matters)
    fields = [
        ("1", "Candidate Name", data.get('candidate_name', '')),
        ("2", "Current location", data.get('location', '')),
        ("3", "Age", data.get('age', '')),
        ("4", "Education Qualification", data.get('education', '')),
        ("5", "Industry Exposure", data.get('industry', '')),
        ("6", "Current Company", data.get('current_company', '')),
        ("7", "Product Selling", data.get('product_selling', '')),
        ("8", "Ticket Size", data.get('ticket_size', '')),
        ("9", "Current Company’s Annual\nSales Target (April-Mar ’25)", data.get('sales_target', '')),
        ("10", "Achieved (April-Mar’25)", data.get('sales_achieved', '')),
        ("11", "Communication", data.get('communication', '')),
        ("12", "Reason for the job change", data.get('reason_change', '')),
        ("13", "Total Experience", data.get('total_exp', '')),
        ("14", "Current salary(Per month)", data.get('current_salary', '')),
        ("15", "Expected Salary (Per month)", data.get('expected_salary', '')),
        ("16", "Notice Period", data.get('notice_period', ''))
    ]

    for sno, label, value in fields:
        # Wrap text
        label_p = Paragraph(label, styles['BodyText'])
        value_p = Paragraph(value, styles['BodyText'])
        table_data.append([sno, label_p, value_p])

    # Table Styling
    # Col widths: S.No (0.5), Field (2.5), Details (4.0)
    t = Table(table_data, colWidths=[0.5*inch, 2.5*inch, 4.0*inch])
    t.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ('BACKGROUND', (0, 0), (-1, 0), colors.whitesmoke), # Header bg
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'), # Center S.No
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)

    # Footer
    story.append(Spacer(1, 30))
    footer = Paragraph("Generated by Triumph Consultants System", ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, alignment=1, textColor=colors.gray))
    story.append(footer)

    doc.build(story)

def convert_to_pdf(input_path, output_path):
    """
    Converts the input file (Image or Docx) to PDF.
    """
    ext = os.path.splitext(input_path)[1].lower()

    if ext == '.pdf':
        if input_path != output_path:
             reader = PdfReader(input_path)
             writer = PdfWriter()
             for page in reader.pages:
                 writer.add_page(page)
             with open(output_path, "wb") as f:
                 writer.write(f)
        return

    if ext in ['.jpg', '.jpeg', '.png']:
        with open(output_path, "wb") as f:
            f.write(img2pdf.convert(input_path))
        return

    if ext in ['.docx', '.doc']:
        try:
            out_dir = os.path.dirname(output_path)
            cmd = ['soffice', '--headless', '--convert-to', 'pdf', input_path, '--outdir', out_dir]
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            
            base_name = os.path.splitext(os.path.basename(input_path))[0]
            generated_pdf = os.path.join(out_dir, base_name + '.pdf')
            
            if generated_pdf != output_path:
                if os.path.exists(output_path):
                    os.remove(output_path)
                os.rename(generated_pdf, output_path)
                
        except (subprocess.CalledProcessError, FileNotFoundError):
            raise RuntimeError("LibreOffice not found or failed. Please run in Docker for Word support.")
        return

    raise ValueError(f"Unsupported file format: {ext}")

    with open(output_path, "wb") as f:
        writer.write(f)

def create_overlay(output_path):
    """
    Creates a single-page PDF with the Header (Logo) and Footer.
    """
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter

    # Header (Logo)
    logo_path = os.path.abspath("static/images/logo.jpg")
    if os.path.exists(logo_path):
        # Draw image at top left (x=30, y=height-100)
        # Reduced size to prevent pixelation: Width 1.5 inch
        c.drawImage(logo_path, 30, height - 90, width=1.5*inch, height=0.8*inch, preserveAspectRatio=True, mask='auto')
    else:
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(colors.HexColor('#2563eb'))
        c.drawString(30, height - 50, "Triumph Consultants")

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.gray)
    c.drawCentredString(width / 2.0, 30, "Generated by Triumph Consultants System")
    
    c.save()

def merge_pdfs(summary_path, resume_path, output_path):
    """
    Merges summary and resume, applying header/footer overlay to ALL pages.
    Scales content pages to fit within margins to avoid overlap.
    """
    from pypdf import Transformation

    writer = PdfWriter()
    
    # Generate Overlay
    overlay_path = os.path.join(os.path.dirname(output_path), "overlay.pdf")
    create_overlay(overlay_path)
    reader_overlay = PdfReader(overlay_path)
    overlay_page = reader_overlay.pages[0]

    # Helper to process and add pages
    def add_pages_with_overlay(reader):
        for page in reader.pages:
            # Scale down content to 75% to fit safely between header and footer
            # Letter size is 612x792
            # 0.75 scale -> ~459x594
            # Margins: 
            #   Top safe area: Header ends at ~height-90. Let's leave space.
            #   Bottom safe area: Footer is at 30.
            #   We center horizontally: (612 - 459)/2 = 76.5
            #   We position vertically: Start above footer. Let's say y=80.
            #   Top of content = 80 + 594 = 674. Header is at >700. Safe.
            
            # Create a blank page of the same size
            new_page = writer.add_blank_page(width=page.mediabox.width, height=page.mediabox.height)
            
            # Apply transformation to the content page
            op = Transformation().scale(0.75).translate(tx=76.5, ty=80)
            page.add_transformation(op)
            
            # Merge scaled content
            new_page.merge_page(page)
            
            # Merge overlay (header/footer) on top
            new_page.merge_page(overlay_page)

    # Add Summary (Already has header/footer from generate_summary_pdf, 
    # but user wants "Every page". 
    # Actually, generate_summary_pdf already adds them using ReportLab. 
    # If we overlay again, it will double up.
    # So for summary, we might NOT need to scale/overlay if it's already correct.
    # BUT, to be consistent, maybe we should remove header/footer from generate_summary_pdf 
    # and use this global overlay? 
    # Let's keep generate_summary_pdf as is for now, assuming it's Page 1 and looks good.
    # The user said "Every page". 
    # Let's apply the overlay ONLY to the resume pages.
    
    # Add Summary (As Is)
    reader_summary = PdfReader(summary_path)
    for page in reader_summary.pages:
        writer.add_page(page)

    # Add Resume (With Overlay and Scaling)
    reader_resume = PdfReader(resume_path)
    add_pages_with_overlay(reader_resume)

    with open(output_path, "wb") as f:
        writer.write(f)
    
    # Cleanup
    if os.path.exists(overlay_path):
        os.remove(overlay_path)
